// Action type constants — import these in actions.js and reducer.js
// to keep string literals consistent across the app.

export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'

// Toast
export const SHOW_TOAST = 'SHOW_TOAST'
export const CLEAR_TOAST = 'CLEAR_TOAST'

// Create Post
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'

// Profile
export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE'

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST'
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE'

export const CHECK_USERNAME_REQUEST = 'CHECK_USERNAME_REQUEST'
export const CHECK_USERNAME_SUCCESS = 'CHECK_USERNAME_SUCCESS'
export const CHECK_USERNAME_FAILURE = 'CHECK_USERNAME_FAILURE'

// List of Values
export const GET_LIST_OF_VALUES_REQUEST = 'GET_LIST_OF_VALUES_REQUEST'
export const GET_LIST_OF_VALUES_SUCCESS = 'GET_LIST_OF_VALUES_SUCCESS'
export const GET_LIST_OF_VALUES_FAILURE = 'GET_LIST_OF_VALUES_FAILURE'
